name: auto_scroll_example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_scroll:
    path: ..

dev_dependencies:
  lint: ^2.0.1

flutter:
  uses-material-design: true
