name: auto_scroll
description: A flexible auto-scrolling widget for Flutter.
version: 0.1.0
homepage: https://github.com/hacker1024/auto_scroll.dart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_resize_observer: ^0.1.0

dev_dependencies:
  lint: ^1.8.2

flutter:
